### ISSUE TITLE
Embedded

### ISSUE THREAD

**Issue by daemonspudguy** [petrucci4prez/CinnXP#23]
I would love to see your embedded theme, but it isn't in compile-theme

**Comment by daemonspudguy** [comment]
@petrucci4prez nothing works but the gtk, either

**Comment by ndwarshuis** [comment]
a) I have no idea what this means. If you are going to post a bug report, please include relevant information including steps to reproduce, applicable version info, etc

b) This branch is moving at the speed of light and should therefore be considered incomplete/unstable (that's why it's a separate branch). Almost nothing has been thoroughly tested yet, and chances are the "bugs" you see will be squashed before this gets merged with master

**Comment by daemonspudguy** [comment]
@petrucci4prez Fair enough, if you want to know, I run Linux Mint 18.1 with gtk.18 and cinnamon 3.2. the panel on Embedded is translucent and the metacity theme is nonexistent (doesn't change anything).

**Comment by daemonspudguy** [comment]
here is a screencap:
![image](https://cloud.githubusercontent.com/assets/24438557/25318536/f435e01c-285e-11e7-81d4-3cec706273d5.png)

**Comment by daemonspudguy** [comment]
@petrucci4prez As I said, I am exited for this to be merged with master.
