### ISSUE TITLE
Blue progressbars in mintupdate

### ISSUE THREAD

**Issue by NikoKrause** [petrucci4prez/CinnXP#27]
That's something I noticed a long time ago, but always forget to ask.
Is there a reason, why mintupdate has blue progressbar with CinnXP?
![bildschirmfoto vom 2017-05-03 11-37-06](https://cloud.githubusercontent.com/assets/8415124/25655483/499a2fd4-2ff5-11e7-8dea-3aa63c62effb.png)

**Comment by ndwarshuis** [comment]
is cinnxp installed in /usr/share/themes? that app runs as root

**Comment by NikoKrause** [comment]
Ah. Cool. Now it works.
I think I saw blue progressbar in mint Software center even when it's installed globally.

Check it later to be sure

**Comment by NikoKrause** [comment]
![screenshot-window-2017-05-07-222139](https://cloud.githubusercontent.com/assets/8415124/25784832/1eeb860c-3374-11e7-8f95-84b593da31cf.png)

mintinstall has a blue progressbar. Not sure if you can do there something.
It's not really important, just something I noticed.

**Comment by NikoKrause** [comment]
Off topic: I saw you worked on LinXP icons. Can you explain how to compile them?

**Comment by Elbullazul** [comment]
@NikoKrause you play supertux too?

**Comment by NikoKrause** [comment]
I just needed something to make a screenshot with. Not played yet.

**Comment by ndwarshuis** [comment]
@NikoKrause the blue progressbar is correct. The software manager must use gtk2 which is why it's solid and not the green/orange thing I could put in gtk3. If you use an eyedropper the color is #316AC5, which is the progressbar color in luna gtk2. This is a limitation in gtk2; if I try the style used in gtk3, the fill will invert when length is shorter than width. Solid fill will hide this problem, at the cost of being marginally more boring (although XP itself still has progressbars that look like this)

![image](https://cloud.githubusercontent.com/assets/6629118/25789327/e2d7d94a-337d-11e7-8dd3-87ae8e96223d.png)

![image](https://cloud.githubusercontent.com/assets/6629118/25789381/4b5cdd4e-337e-11e7-96b0-a7045617e468.png)



Regarding LinXP, I will update README shortly

**Comment by NikoKrause** [comment]
Thanks for the explanation.

**Comment by NikoKrause** [comment]
@petrucci4prez 
I tried to compile LinXP on LM 18.1, but I get the following error message:
```
Traceback (most recent call last):
  File "./compile_icon_theme.py", line 118, in <module>
    compileIcons(os.path.join(rootpath, group))
  File "./compile_icon_theme.py", line 43, in compileIcons
    os.makedirs(out, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
```

**Comment by ndwarshuis** [comment]
@NikoKrause please open on the LinXP repo with relevant version info
