### ISSUE TITLE
CinnXP missing gtk3 theme in tab mix plus

### ISSUE THREAD

**Issue by llpub** [petrucci4prez/CinnXP#30]
tab mix plus is a firefox addons. CinnXP works well for tab mix plus when firefox uses gtk2.
Recently firefox migrated from gtk2 to gtk3. Tab mix plus in firefox (gtk3) has broken theme under CinnXP. 
For other themes(e.g. Adwaita), gtk3 themes worked for tab mix plus.
P.s. debian9, gtk3.22
![gtk3bug](https://user-images.githubusercontent.com/25077000/27768823-fe444bc6-5f4e-11e7-8350-189cf002de80.png)

**Comment by ndwarshuis** [comment]
Firefox still does not have full support for gtk3.20+ (see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1264079)). The adwaita theme does not really "work"; tabs in tab mix plus look totally different compared to legit notebook widgets in other apps (shadows, blue underscore, background, etc). As it turns out, firefox tabs pull in the frame color, which is fine for adwaita but puts an ugly box around CinnXP notebooks:

gtk3-widget-factory
![image](https://user-images.githubusercontent.com/6629118/27772453-0404f7ea-5f31-11e7-9d16-c8b280b906ea.png)

tab mix plus
![image](https://user-images.githubusercontent.com/6629118/27772454-09b8fccc-5f31-11e7-883f-42725c7d582d.png)

All that to say this is not a CinnXP bug and there are no viable workarounds I can do. Not my job to conform to potentially non-standard addons built for non-standard apps. If you want the tabs to look nice, use firefox compiled with gtk2 (or wait till the firefox devs update to the new gtk3.20 standard)

**Comment by llpub** [comment]
Thank you.
