### ISSUE TITLE
headerbar buttons?

### ISSUE THREAD

**Issue by Elbullazul** [petrucci4prez/CinnXP#7]
hi there, 

love this theme. I've been myself working on the "missing" variants you have on your to do list, and one thing I miss from your theme are the headerbar buttons. For example:
- here's my embedded version:
  ![screenshot_2016-09-29_08-04-04](https://cloud.githubusercontent.com/assets/15310985/19189964/b7647582-8c68-11e6-963e-2c0dd3e97241.png)
- and here's the CinnXP theme (3.18):
  ![screenshot_2016-10-07_08-33-49](https://cloud.githubusercontent.com/assets/15310985/19189979/d4b461d8-8c68-11e6-8af5-07442af8c41a.png)

is it possible for you to make those buttons looke like the original luna theme, and to include the window-decoration gradient on the headerbar? 

Tip: to get the effects only on titlebars, you can use the `.titlebar` class

cheers,

**Comment by NikoKrause** [comment]
Which OS do you use and how do you have compiled the CinnXP theme.

The newest github verison of CinnXP uses GTK 3.20.
If you are using LinuxMint18, which uses GTK 3.18, you have to change the following line in the `compile-theme` file.
Change the `20` in this line to `18`:
`gtk3_minor_revision=20`

**Comment by ndwarshuis** [comment]
@Elbullazul Tried what you did first, and eventually decided it looked too weird and wasn't worth the effort IMHO. Yes I am aware of .titlebar class, and in this case I chose to make the titlebars look like toolbars as I think they resemble a toolbar more than a titlebar (they are about the same width as a toolbar and usually have lots of buttons on them)

As far as not being worth the effort, I can tell you now there will be ALOT of specialized code required to do what you want. For example, look at Evince. You'll see buttons, entries, buttons linked to other buttons, entries linked to buttons, etc in addition to the flat buttons you already changed (and there could be more, like spin buttons, that appear in other apps). This means you'll need specialized .titlebar .widget.something.somethingelse for all of these. It's doable, but will be hard to implement and even harder to maintain.

One thing you'll notice if you look at my code is it actually varies from Adwaita very little (at last the massive _common.scss file) . I basically used their skeleton and changed the background, border radius, etc. This essentially allows me to do a 3-way diff whenever I need to update gtk versions and change each section accordingly. Updating will become exponentially harder the more you deviate from Adwaita (because it WILL break as we all unfortunately know), and your proposed code will naturally be at odds with the GNOME maintainers.

**Comment by Elbullazul** [comment]
@NikoKrause I used the 3.18 pre-compiled theme from gnome-look

@petrucci4prez I kind of like the way you work. Thanks for your quick answer and for taking time to explain your point of view

**Comment by dominichayesferen** [comment]
@petrucci4prez If you don't like images on headerbars, you can always try gradients
